from config import ENVIRONMENT, QA_CONSTANTS

if ENVIRONMENT == "qa":
    CONSTANT = QA_CONSTANTS
# elif ENVIRONMENT == "stg":
#     CONSTANT = STG_CONSTANTS
# else:
#     CONSTANT = PROD_CONSTANTS

TOKEN_URL               = CONSTANT['TOKEN_URL']
PRISM_TOC_API           = CONSTANT['PRISM_TOC_API']
PRISM_PAGE_MAPPING_API  = CONSTANT['PRISM_PAGE_MAPPING_API']
CSG_PRODUCT_API         = CONSTANT['CSG_PRODUCT_API']
COURSE_API              = CONSTANT['COURSE_API']
RESOURCE_API            = CONSTANT['RESOURCE_API']

#Login
# TIBRON_USERNAME   =  CONSTANT['TIBRON_USERNAME']
# TIBRON_PASSWORD   =  CONSTANT['TIBRON_PASSWORD']

#Login API Specific
# USERNAME   =  CONSTANT['USERNAME']
# PASSWORD   =  CONSTANT['PASSWORD']

# Other constant
PRODUCT_ID = 'productId.txt'
GENERATE_CSV_FILE_NAME = 'generated_report.csv'